--Step: 5 
--Magnitude exploration
--
--Find total customers by countries
SELECT country , COUNT(customer_key) AS  CustomersbyCountry  FROM gold.dim_customers GROUP BY country ORDER BY CustomersbyCountry DESC
--Find total customers by gender
SELECT gender , COUNT(customer_key) AS  CustomersbyGender  FROM gold.dim_customers GROUP BY gender ORDER BY CustomersbyGender  DESC
--Find total products by category
SELECT category, COUNT(product_key) AS ProductsbyCategory FROM gold.dim_products GROUP BY category ORDER BY ProductsbyCategory DESC
--What is the average costs in each category?
SELECT category, AVG(cost) AS AvgCostbyCategory
FROM gold.dim_products
GROUP BY category
ORDER BY AvgCostbyCategory DESC
--What is the total revenue generated for each category?

SELECT dp.category, SUM(sales_amount) AS totalrevenuebycategory
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON dp.product_key = fs.product_key
GROUP BY dp.category
ORDER BY totalrevenuebycategory DESC

--Find total revenue generated by each customer
SELECT 
	dc.customer_key, 
	dc.first_name,
	dc.last_name,
	SUM(fs.sales_amount) AS totalrevenuebycustomers 
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY 
	dc.customer_key, 
	dc.first_name,
	dc.last_name
ORDER BY totalrevenuebycustomers DESC
--What is the distribution of sold items across countries?
SELECT 
	dc.country,
	SUM(fs.quantity)AS totalquantitybycountry
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY totalquantitybycountry DESC
